'use client';
import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { Clock3, UserRoundPlus } from 'lucide-react';
import WorkspaceHeader from '../../../../components/WorkspaceHeader';
import { createClient } from '../../../../lib/supabase/client';

export default function Page(){
  const {id}=useParams<{id:string}>();
  const [people,setPeople]=useState<any[]>([]),[entries,setEntries]=useState<any[]>([]),[email,setEmail]=useState(''),[name,setName]=useState(''),[role,setRole]=useState('staff'),[msg,setMsg]=useState('');
  async function load(){const sb=createClient();const [{data:p},{data:t}]=await Promise.all([sb.from('club_users').select('id,role,active,user_id,profiles(full_name,email)').eq('club_id',id),sb.from('staff_time_entries').select('*,profiles(full_name)').eq('club_id',id).order('clock_in',{ascending:false}).limit(30)]);setPeople(p||[]);setEntries(t||[])}
  useEffect(()=>{load()},[id]);
  async function invite(){if(!email)return;const sb=createClient();const normalized=email.trim().toLowerCase();const {data:{user}}=await sb.auth.getUser();let token:string|undefined;const {data:existing}=await sb.from('club_invitations').select('id,token').eq('club_id',id).eq('email',normalized).eq('status','pending').maybeSingle();if(existing){const {data,error}=await sb.from('club_invitations').update({full_name:name,role,invited_by:user?.id,expires_at:new Date(Date.now()+7*24*60*60*1000).toISOString()}).eq('id',existing.id).select('token').single();if(error)return setMsg(error.message);token=data.token}else{const {data,error}=await sb.from('club_invitations').insert({club_id:id,email:normalized,full_name:name,role,invited_by:user?.id}).select('token').single();if(error)return setMsg(error.message);token=data.token}const url=`${(process.env.NEXT_PUBLIC_APP_URL||'https://app.nadorio.com').replace(/\/$/,'')}/join?token=${token}`;const {data:{session}}=await sb.auth.getSession();const sent=await fetch('/api/email/invite',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({token})});if(sent.ok)setMsg(existing?'Existing invitation updated and resent successfully.':'Invitation created and emailed successfully.');else{await navigator.clipboard?.writeText(url);setMsg('Invitation saved, but email failed. NADORIO link copied instead.')}setEmail('');setName('');load()}
  async function clock(){const sb=createClient();const {data:{user}}=await sb.auth.getUser();if(!user)return;const {data:open}=await sb.from('staff_time_entries').select('*').eq('club_id',id).eq('user_id',user.id).is('clock_out',null).maybeSingle();if(open)await sb.from('staff_time_entries').update({clock_out:new Date().toISOString()}).eq('id',open.id);else await sb.from('staff_time_entries').insert({club_id:id,user_id:user.id});load()}
  return <><WorkspaceHeader title="Staff & Team" subtitle="A simple home for team access, invitations and time tracking"/><div className="staffV43Grid"><section className="staffClockCard"><Clock3 size={34}/><div className="eyebrow cyan">MY WORKDAY</div><h2>Time clock</h2><p>Clock in when your shift starts and clock out when you’re finished. Your recent entries stay available below.</p><button className="staffClockButton" onClick={clock}>Clock In / Clock Out</button></section><aside className="staffInviteCard"><UserRoundPlus size={28}/><h2>Invite your team</h2><p>Add a club administrator, manager or staff member.</p><div className="staffInviteFields"><input placeholder="Full name" value={name} onChange={e=>setName(e.target.value)}/><input type="email" placeholder="Email address" value={email} onChange={e=>setEmail(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value)}><option value="admin">Club Admin</option><option value="manager">Manager</option><option value="staff">Staff</option></select><button className="button gradient" onClick={invite}>Send Invitation</button></div>{msg&&<div className="successMsg">{msg}</div>}</aside></div><section className="staffTableCard"><div className="staffTableHead"><h2>Your team</h2><p>Everyone with staff or administrative access to this club.</p></div>{people.map(p=>{const n=p.profiles?.full_name||'User';return <div className="staffPersonRow" key={p.id}><div className="staffPersonAvatar">{n.split(' ').map((x:string)=>x[0]).slice(0,2).join('').toUpperCase()}</div><div><b>{n}</b><small>{p.profiles?.email||p.user_id}</small></div><span className="staffRole">{p.role}</span><span className="staffActive">{p.active?'Active':'Inactive'}</span></div>})}</section><section className="staffTableCard"><div className="staffTableHead"><h2>Recent time entries</h2><p>Latest clock-in activity across your team.</p></div>{entries.map(x=><div className="datarow" key={x.id}><b>{x.profiles?.full_name||'Staff'}</b><span>{new Date(x.clock_in).toLocaleString()}</span><span>{x.clock_out?new Date(x.clock_out).toLocaleString():'Currently clocked in'}</span></div>)}{!entries.length&&<div className="empty">No time entries yet.</div>}</section></>;
}
